### ISSUE TITLE
Lazy Loading For Singleton Pattern

### ISSUE THREAD

**Issue by jonathancoding** [RaymondXu/JavaWorkshop#1]
Hi Raymond,

I love your JavaWorkshop! By the way, can you add lazy loading feature singleton pattern ?
https://en.wikipedia.org/wiki/Initialization-on-demand_holder_idiom

**Comment by raymondxu** [comment]
Thanks for the feedback. Added: 72b5adcb1639084a7788768d68bc7e7665d33ece!
